version: '1'

services:
   nginx-proxy:
     image: nginxproxy/nginx-proxy
     publish: 
      - "80:80"
      - "443:443"
     volumes:
       - certs:/etc/nginx/certs
       - vhost:/etc/nginx/vhost.d
       - html:/usr/share/nginx/html
       - /var/run/docker.sock:/tmp/docker.sock:ro
     restart: always

   acme-companion:
     depends_on:
       - nginx-proxy
     image: nginxproxy/acme-companion
     volumes_from:
     - nginx-proxy
     volumes: 
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - acme:/etc/acme.sh
     restart: always
     environment:
       DEFAULT_EMAIL: gen@genomx.be

volumes:
    certs:
    vhost:
    html:
    /var/run/docker.sock:
    acme: