version: '1.27'

services:
   nginx-proxy:
     image: nginxproxy/nginx-proxy
     ports: 
       - "80:80"
       - "443:443"
     volumes:
       - type: volume
         source: certs
         target: /etc/nginx/certs
       - type: volume
         source: vhost
         target: /etc/nginx/vhost.d
       - type: volume
         source: html
         target: /usr/share/nginx/html
       - type: volume
         source: docker-sock
         target: /tmp/docker.sock
         read_only: true
     restart: always

   acme-companion:
     depends_on:
       - nginx-proxy
     image: nginxproxy/acme-companion
     volumes_from:
       - nginx-proxy
     volumes: 
       - type: volume
         source: docker-sock
         target: /var/run/docker.sock
         read_only: true
       - type: volume
         source: acme
         target: /etc/acme.sh
     restart: always
     environment:
       DEFAULT_EMAIL: gen@genomx.be

volumes:
    certs:
    vhost:
    html:
    docker-sock:
    acme: