version: '3.3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy-m3
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: certs
        target: /etc/nginx/certs
      - type: volume
        source: vhost
        target: /etc/nginx/vhost.d
      - type: volume
        source: html
        target: /usr/share/nginx/html
      - type: bind
        source: /var/run/docker.sock
        target: /tmp/docker.sock
        read_only: true
    restart: always
  acme-companion:
    depends_on:
      - nginx-proxy
    image: nginxproxy/acme-companion
    container_name: acme-companion-m3
    volumes_from:
      - nginx-proxy
    volumes: 
      - type: volume
        source: acme
        target: /etc/acme.sh
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    restart: always
    environment:
      DEFAULT_EMAIL: gen@genomx.be
volumes:
  certs:
  vhost:
  html:
  acme: