version: '3.3'
services:
  bio-r:
    image: unam-uime_bio-r:3_16
    container_name: bio-r-3_16
    hostname: genomx
    ports:
      - target: 8787
        published: 8787
        protocol: tcp
        mode: host
    volumes:
      - /Data/A/dockerapps/bio-r:/Data:ro
      - /home/:/home/
      - /public/:/public/
      - /apps/:/apps/
      - site-library_3_16:/usr/local/lib/R/host-site-library
    restart: always
networks: 
  default: 
    external: 
      name: ume-pub 
volumes:
  site-library_3_16:
