version: '3.3'
services:
  bio-r:
    image: bio-r:devel
    container_name: bio-r-3_16
    hostname: ume-53
    ports:
      - 0.0.0.0:8787:8787
    expose:
      - "8787"
    volumes:
      - /home/:/home/
      - /public/:/public/
      - /apps/:/apps/
      - /orgs/:/orgs/
      - /mnt/d01/mcps/:/orgs/mcps/data
      - site-library_3_16:/usr/local/lib/R/host-site-library
      - /opt/R/:/opt/R
    restart: unless-stopped
    env_file: .rstudio.env
    environment:
      VIRTUAL_HOST: bio-r.genomx.be
      LETSENCRYPT_HOST: bio-r.genomx.be
networks: 
  default: 
    external: 
      name: ume-pub 
volumes:
  site-library_3_16:
