version: '3.3'
services:
  jupyter:
    image: unam-uime-jupyter:jupyter
    container_name: jupyter
    user: root
    ports:
      - target: 8888
        published: 8888
        protocol: tcp
        mode: host
    volumes:
      - /Data/A/dockerapps/jupyter:/Data:ro
      - /home/:/home/
      - site-library_m3:/opt/conda
    restart: always
    environment:
      NB_USER: gen
      NB_GID: 1101
      CHOWN_HOME: 1
      VIRTUAL_HOST: jupyter.genomx.be
      LETSENCRYPT_HOST: jupyter.genomx.be
    working_dir: /home/gen

networks: 
  default: 
    external: 
      name: ume-pub 
volumes:
  site-library_m3: