version: '1.0'
# Falta especificar algunos parámetros, pero no sé donde van (--user root) ( -w "/home/${NB_USER}")
# Y asignar directorio local para mapear el opt/conda
services:
   jupyter:
     image: unam-uime-jupyter:jupyter
     volumes:
       - /Data/A/dockerapps/jupyter:/Data:ro
       - /home/:/home/
       - /ruta_de_conda_dir_de_nuestro_lado/:/opt/conda
     restart: always
     ports:
       - "8888:8888"
     environment:
       NB_USER: gen
       NB_GID: 1101
       CHOWN_HOME: yes
       VIRTUAL_HOST: jupyter.genomx.be
       LETSENCRYPT_HOST: jupyter.genomx.be

volumes:
    volume certs:
    /Data/A/dockerapps/jupyter:
    /ruta_de_conda_dir_de_nuestro_lado/: 